---
- hosts: all
  sudo: true
  tasks:

    - name: Add /etc/hosts vagrant environment nodes
      lineinfile: dest=/etc/hosts
                  line={{ item.line }}
                  insertafter={{ item.insertafter }}
      with_items:
        - { line: "# vagrant environment nodes",               insertafter: EOF }
        - { line: "192.168.56.155  ansiserver.local.internal", insertafter: "^# vagrant environment nodes" }
        - { line: "192.168.56.156  opendj.local.internal",     insertafter: '^192.168.56.155  ansiserver.local.internal' }



